// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/golf-audiences/Current.tsx": () => import("../components/mockups/golf-audiences/Current.tsx"),
  "./components/mockups/golf-audiences/Refined.tsx": () => import("../components/mockups/golf-audiences/Refined.tsx"),
  "./components/mockups/platform-comparison/Current.tsx": () => import("../components/mockups/platform-comparison/Current.tsx"),
  "./components/mockups/platform-comparison/Refined.tsx": () => import("../components/mockups/platform-comparison/Refined.tsx"),
  "./components/mockups/how-it-works/Current.tsx": () => import("../components/mockups/how-it-works/Current.tsx"),
  "./components/mockups/how-it-works/Refined.tsx": () => import("../components/mockups/how-it-works/Refined.tsx")
};
